services:
  - type: web
    name: ml-service
    env: python
    buildCommand: |
      rm -rf /opt/render/project/src/.python-poetry
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k uvicorn.workers.UvicornWorker ml_service:app
    pythonVersion: 3.10.13
